elementary/mail

- src/client/composer/composer-widget.vala
This fixes a regression I've noticed after the previous commit.
Before this commit, in the composer, if you use one of the shortcuts for the toggleable actions (like Ctrl+B for Bold). The related button in the toolbar doesn't toggle its state until you start typing.
This branch resolves this.
> Ensure actions states are updated once triggered

- data/application.css
- data/io.elementary.mail.gresource.xml
- meson.build
- src/Application.vala
- src/ConversationList/ConversationListItem.vala
- src/meson.build
This adds a gresource and moves CSS out of the ConversationListItem into an application css stylesheet. This should prevent creating multiple style providers inside the application later on and making sure there's a centralized place to view all application CSS styles.
> Move CSS to an external stylesheet

- src/ConversationList/ConversationListItem.vala
- src/meson.build
This duplicates the functionality from https://github.com/elementary/mail/blob/master/src/client/util/util-date.vala
Show messages received:
> Display relative date time in conversation list

- src/MessageList/MessageListItem.vala
- src/WebView.vala
Ensure we pull any mime parts out of the message that are marked as `inline`. This allows us to display attachments inline in the WebView as well as the ones that are loaded from web URLs.
> Load inline images

- data/io.elementary.mail.gschema.xml
- src/MessageList/MessageListItem.vala
- src/WebView.vala
- src/WebViewServer.vala
- webkit-extension/Main.vala
Add two settings keys, one to always allow image loading (defaults to true), another as an email address whitelist of  sender addresses for which remote images will be automatically loaded.
I've not added any UI for controlling the settings keys, nor have I added the infobar that will show when images are blocked (though I have left a TODO comment on the signal where that would be).
> Remote image blocking

- po/POTFILES
- src/Dialogs/OpenAttachmentDialog.vala
- src/MessageList/AttachmentBar.vala
- src/meson.build
* Rename to resolve ambiguity with future FileDialog subclass
* Move to `Dialogs` as in other elementary apps
* Fix styling, sizing
* Resolve terminal warnings about no transient parent, etc
> Open attachment dialog fixes

- src/MainWindow.vala
Noticed that there's a little black box in the bottom right when you start mail. The URL overlay thing wasn't initially hidden.
> Hide empty URL overlay

- src/client/conversation-viewer/conversation-viewer.vala
> Prevent ScrolledWindow scrolling to the top when webview is focused

- webkit-extension/Main.vala
This would have been throwing up some blocked image infobars on emails that didn't have images.
> Add a missing allowed scheme

- src/HeaderBar.vala
Depends on https://github.com/elementary/stylesheet/pull/153 to be styled correctly
There's only one real preference at this time, so no dialog. If/when there are more preferences we can do a dialog, but if there's only a couple settings this is just faster and easier, imo. If we end up having more of these switch menu items, I'll refactor that into a widget class
Account settings are all external, so assume that the system online accounts settings knows what to do.
> Add preferences menu

- src/ConversationList/ConversationListItem.vala
Fixes a mistake that caused the time format to be returned instead of the formatted time
> Return formatted time, not time format

- po/POTFILES
- src/Composer/ComposerWidget.vala
- src/Composer/ComposerWindow.vala
- src/meson.build
This supersedes part of #115. Just splitting it into parts to get a cleaner diff. This first part is a straight cut and paste of the widgets that will be used in both the inline and separate composers (so, the formatting bar and the webview).
> Move re-usable parts of composer into separate widget

- src/ConversationList/ConversationListItem.vala
It looks like `-gtk-icon-palette` doesn't allow custom variables, so we can cheat and use a style class:
Requires this branch: https://github.com/elementary/stylesheet/pull/163
> Add attention class to unread icon

- src/engine/imap-db/imap-db-database.vala
- src/engine/imap-db/imap-db-message-row.vala
- src/engine/imap/message/imap-internal-date.vala
- src/engine/rfc822/rfc822-message-data.vala
Fixes #184 
Looks like my editor went and cleaned up a load of trailing whitespace, but it's a simple patch taken from [here](https://github.com/GNOME/geary/commit/383ee159928386e7ed9b7265f8c5863514a0dab7) and [here](https://github.com/GNOME/geary/commit/756cc39d8de0f1b1340ba963274e5073b99515ba).
> Don't use time_t as a property

- src/MessageList/MessageListItem.vala
- src/WebView.vala
I couldn't read plain text mails in my inbox and tracked it down to two issues:
* The messages were ISO-8859 encoded, and WebView.load_plain_text fails on invalid UTF-8 strings. I have fixed this by converting message contents to UTF-8 where they are loaded.
* WebView.load_plain_text was not overridden to set the load_changed handler like WebView.load_html. I've added an implementation using Camel's text-to-HTML filter.
Re: encoding stuff, it feels odd to have so much model logic in MessageListItem. Should I move the asynchronous message decoding to a helper class?
> EDS rewrite: Correct encoding, display plain text emails

- src/Backend/Session.vala
- src/ConversationList/ConversationListBox.vala
- src/HeaderBar.vala
- src/MainWindow.vala
- src/MessageList/MessageListBox.vala
I've introduced a new property `can_move` which is similar to `can_reply` and determines whether the selected conversation can be moved. This branch only implements the case of moving a conversation to the trash, not to arbitrary branches.
Clicking the trash button while inside the trash folder does not do anything right now, so messages cannot be fully deleted right now.
I've had to disable selection of multiple conversations right now. I think the way to go would be to move & rename the `MessagesListBox.uids` property to `ConversationListBox.selected_uids`. Then both MessagesListBox and the MainWindow would figure out which messages are selected by looking at this property, and the MessagesListBox wouldn't have to deal with FolderThreadNode iteration at all.
> Move messages to trash

- webkit-extension/Main.vala
Fixes DBus error warnings by throwing at least a GLib.Error
> Fix DBus error warnings

- data/io.elementary.mail.gschema.xml
- src/Application.vala
- src/MainWindow.vala
* Make use of gsettings for setting the default window size and make this match the old default
* Make the sidebar width match Files
* Remove a now unnecessary check and re-use a rect
* Change the minimum size so that Mail can be tiled on a smaller laptop display. Fixes #173
> Change default and minimum window sizes

- src/ConversationList/ConversationListItem.vala
Fixes an issue with markup being used in some sender names
> ConversationListItem: Set use markup on source label

- src/Application.vala
- src/MainWindow.vala
Fixes #297 
Override the window configure event and save window state when it's changed, but throttle it so we don't thrash the disk.
> Save state on configure event, throttled

- src/Composer/ComposerWidget.vala
- src/ConversationList/ConversationListItem.vala
- src/HeaderBar.vala
- src/Utils.vala
Uses the new tooltip markup style that we discussed this morning in #UX 
I've temporarily added two utils that were recently merged into granite [here](https://github.com/elementary/granite/commit/07afa7ac0cbdf1d6dd923d5392722c54665af0c5). I figure we can easily remove those utils once a new Granite release comes out.
> Set tooltip accel markup

- src/Composer/ComposerWidget.vala
I think all actions above the web view are expected to do something with the selection in the webview or at least at the current cursor position of the webview, so make sure we only enable them when there's a cursor in there.
> Bind composer action sensitivity to web view focus

- src/Composer/ComposerWidget.vala
Seems like this change wasn't actually tested. This makes it impossible to activate any of these actions since clicking any of the toolitems necessarily moves focus but it also makes it impossible to use keyboard navigation to activate any of the toolitems.
Some of these items should probably be insensitive when there is no selection in the webview, but checking focus makes it unusable
> Revert #310

- po/POTFILES
- src/MainWindow.vala
- src/WelcomeView.vala
- src/meson.build
Adds a welcome screen that links to Online Accounts.
Need to add a signal listener to show/hide the appropriate screen depending on if accounts are configured in EDS.
> Add a welcome screen

- src/Application.vala
Gets rid of a couple extra variables and write directly to the allocation rectangle
> Application: Make restore state code more concise

- src/Application.vala
- src/MainWindow.vala
Because it has a built-in action group.
According to the docs, `add_window` is the same as setting the `application` property of `Gtk.ApplicationWindow`
> MainWindow.vala: subclass Gtk.ApplicationWindow

- README.md
Since I've heard a few people asking how to help test, and according to the UI it looks like the Online Accounts integration should just work. This can be removed from the README once setting up and Online Account actually makes email accounts accessible to Camel/EDS.
> Add account instructions to README

- src/ConversationList/ConversationListItem.vala
This fixes an issue where sometimes we'd have little black unread icons next to read emails
> ConversationListItem: Make sure we hide status when appropriate

- src/MainWindow.vala
Hello! I liked how Terminal, Code, Epiphany supported true full screen and wanted to have the same with Mail. I use full screen on many of my applications so it's easy to switch using workspaces and have it feel like the entire workspace is dedicated to just that app.
I am not sure if the HIG says that the `HeaderBar` should not be visible when in full screen mode (I noticed it is hidden on Code and Epihany), but core functionality was hidden away so I made the `HeaderBar` visible in full screen mode in my PR.
> Full screen support

- data/blank-message-template.html
Cribbing from Geary here, to use the `dir="auto"` attribute on the containing `div` in the composer web view. This uses the "first strong" heuristic: the first letter in the text with a clear directionality determines the overall text direction. One _could_ get more clever, but even Apple Mail uses this simple rule.
Note that the subject field, and probably other native text widgets, already handle bidirectional text correctly.
> #389 don't assume left-to-right text ordering

- src/Application.vala
- src/Composer/ComposerWidget.vala
- src/Composer/ComposerWindow.vala
Doing it this way we simplify the number of arguments we're passing by quite a bit and we keep ComposerWidget to be a more strict GObject style
Also add BCC support
> Wait to parse mailto until ComposerWidget

- src/Application.vala
This also allows weirdness like `mailto:?cc=foo@example.com`, but that seems fine if someone really wants to do that.
> Allow empty mailto: URL, so compose menu item in Dock will work (#400)

- src/ConversationList/ConversationListBox.vala
I'll try to fix the underlying bug in GTK this weekend, but it could be a while before a fixed upstream library is available.
Fixes #396
> #396: work around bug with action groups in GTK, to avoid a crash

- src/ConversationList/ConversationListBox.vala
- src/FoldersView/AccountSourceItem.vala
- src/WebView.vala
Listen to the network availability to refresh the folder.
Allow to list folders even when offline.
Special-case cancelled operations to avoid filling the logs with "Operation cancelled" errors
> AccountSourceItem: List folders before going online and refreshing them

- src/Composer/ComposerWidget.vala
Fixes #394 
Use `Camel.text_to_html` to convert a `body` query parameter on `mailto:` URLs. We set up the flags to automatically convert URLs and email addresses into hyperlinks and line breaks and space characters into the relevant HTML entities.
While I was here, I converted the query parameter key to lowercase so we're case insensitive about the query parameters.
> Support body parameter for mailto URLs

- src/MainWindow.vala
Fixes #359 
Note: we don't disable the _actions_ when we lose keyboard focus, because we probably still want the buttons in the toolbar to delete the selected message? We just want the keyboard to not be able to trigger those actions anymore.
> Disable delete accels on loss of keyboard focus

- src/HeaderBar.vala
Continuing the conversation from https://github.com/elementary/notifications/pull/80 with a more complicated example
`load_images_grid` is intentionally not altered because of #495
> HeaderBar: Initialize objects with properties

- data/application.css
- src/Composer/ComposerWidget.vala
So we don't have to add a `.entry` class to the stylesheet
> ComposerWidget: Use css_name to style to entry

- src/VirtualizingListBox/VirtualizingListBox.vala
We were seeing some buggy selection state behaviour in the conversation list box when the list refreshed or was updated. This helps to resolve some/most of these issues.
> Ensure selection state is unset on recycled widgets

- src/ConversationList/ConversationItemModel.vala
- vapi/camel-1.2.vapi
Also update the related Camel VAPI with upstream one to avoid type cast.
> ConversationItemModel: Do not set FolderThreadNode as GObject property

- src/Backend/Session.vala
- src/ConversationList/ConversationItemModel.vala
This fixes some crashes.
Also reduce unnecessary string duplication and reference increase
> ConverstionItemModel: Make sure to never use a null Camel.MessageInfo

- src/MainWindow.vala
At the moment, the main window doesn't have a title. It is not a big deal since the title is not displayed anywhere in the UI.
However, once https://github.com/elementary/gala/issues/798 gets fixed, Gala will display "io.elementary.mail" as window title.
> Add window title

- io.elementary.mail.yml
* Restrict filesystem access to `/tmp/io.elementary.mail` and define it as TMPDIR for the opening attachments.
* Remove unused EDS DBus addresses.
* Support dark theme.
* Use granite from master.
* Update dependencies.
> Update flatpak manifest

- src/ConversationList/ConversationListBox.vala
- src/FoldersView/FoldersListView.vala
- src/FoldersView/GroupedFolderSourceItem.vala
- src/FoldersView/SessionSourceItem.vala
- src/MainWindow.vala
This PR adds the infrastructure to support different kind of grouped folders. It builds upon #571 and uses the `Camel.FolderInfoFlag.TYPE_*` enum to decide which grouped folder should be rendered.
The only pieces missing are figuring out the folder specific `full_name` attribute per account. This has already been solved in the first attempt of the grouped inbox - but the code did not make its way into master because we dropped it in order to make review easier:
https://github.com/elementary/mail/blob/a75adfd100fe9dcef98d700b7230b466f91fd2e7/src/FoldersView/GroupedFolderSourceItem.vala
> Grouped Folders: Made Type Configurable

- src/FoldersView/GroupedFolderSourceItem.vala
- src/FoldersView/SessionSourceItem.vala
This PR re-adds the unified Sent folder. However, we do have two issues to solve with the current implementation:
```
(gdb) backtrace
#0  0x00007f558862c434 in camel_message_info_get_date_received () at /lib/x86_64-linux-gnu/libcamel-1.2.so.62
#1  0x0000562d66f7e2ef in mail_conversation_item_model_get_newest_timestamp (node=0x7ffc405cc4c0, highest=1537724696)
at ../src/ConversationList/ConversationItemModel.vala:168
#2  0x0000562d66f7e4a7 in mail_conversation_item_model_get_newest_timestamp (node=0x7ffc405cc620, highest=1537724696)
at ../src/ConversationList/ConversationItemModel.vala:173
#3  0x0000562d66f7e4a7 in mail_conversation_item_model_get_newest_timestamp (node=0x7ffc405cc780, highest=1537724696)
at ../src/ConversationList/ConversationItemModel.vala:173
#4  0x0000562d66f7e4a7 in …
```
> Grouped Folders: Sent

- src/Composer/ComposerWidget.vala
Until we can get #384 fixed up, this at least makes the composer UI honest with what buttons and shortcuts are available and work
> Composer: Remove unused buttons and bad shortcuts

- data/icons/mail-drafts/16.svg
- data/icons/mail-drafts/48.svg
- data/io.elementary.mail.gresource.xml
- src/Application.vala
- src/Composer/ComposerWidget.vala
- src/FoldersView/FolderSourceItem.vala
Thought it would be nice to use a badged icon for dialogs here and I noticed that we don't have a 48px drafts icon and we were actually using folder-documents for drafts. So gresource some specific icons
> Add Drafts icons

- src/ConversationList/ConversationListBox.vala
The crash described in #608 is caused by some asynchronous voodoo, where `folders[service_uid]` is already freed at the time when `get_search_result_uids ()` tries to access it.
This PR mitigates the issue by adding the following safety measures:
1. Set `folders[service_uid] = folder` before binding to folder.changed signal - just to be sure (swapped lines 146 and 147)
2. get_search_result_uids function locks the `folders` HashMap during its executing to prevent changes
3. get_search_result_uids function checks for existence of `folders[service_uid]` - if it does not exists, it returns `null`
4. Callers of the get_search_result_uids function handle the `null` case gracefully
> Fixes #608: Random crash when changing folder

- data/io.elementary.mail.appdata.xml.in
- src/Composer/ComposerWidget.vala
- src/WebView.vala
This is a naive approach to detect changes made to a draft or a newly created message. It simply sets the changed flag whenever a key was pressed in the composer or a command was executed (bold, italic etc.)
Although this is not 100% correct at all times, it seems to work well enough - and I did not found any better solution.
> Fix #619: Don't save draft if no changes were made

- webkit-extension/MailPage.vala
This PR fixes #582 by correctly calculating the page height of an email as the previously used method failed under certain circumstances.
We now just use the max height available. Solution inspired by this StackOverflow post: https://stackoverflow.com/questions/1145850/how-to-get-height-of-entire-document-with-javascript#answer-1147768
> Fix #582: Calculate the page height correctly

- README.md
Because on Odin this is no longer valid. Online Accounts now allows for setting up the mail account.
Was brought up in https://github.com/elementary/mail/issues/650#issuecomment-902275359
> README: Removed Evolution account setup hint

- src/ConversationList/ConversationItemModel.vala
Avoids using freed nodes when `ConversationListStore` uses it's `compare_func`.
Fixed the `camel_message_info_get_date_received: assertion 'CAMEL_IS_MESSAGE_INFO (mi)' failed` errors for me (#649, #650 , #652).
Note: `folder_changed` updates *every* conversation in the folder, so is expensive when a folder has a large number of items. So for example, setting a message as read will ultimately mean `folder_changed` fires and touches every conversation. I can't see a way around it at the moment though.
> Cache timestamp to avoid compare_func from crashing

- data/daemon.desktop
- data/meson.build
Since we're not doing anything fancy, I don't think we need that `config` step
Also, I don't think we need keywords here since autostart files aren't searchable afaik
Simplify the file name while we're here because meson lets us do that and it's convenient finding the right file in the sidebar of Code
> Meson: rename daemon and remove config

- src/Composer/ComposerWidget.vala
The changes in this PR basically re-adds support for attachments in mailto queries. This is needed for https://github.com/elementary/files/pull/1822 to work.
Fixes https://github.com/elementary/mail/issues/666 together with https://github.com/elementary/files/pull/1822. Supersedes https://github.com/elementary/mail/pull/674.
> Add Support for the org.freedesktop.portal.Email portal

- data/io.elementary.mail.appdata.xml.in
- src/Backend/Session.vala
Follow up of https://github.com/elementary/mail/pull/625. Fixes https://github.com/elementary/mail/issues/465
@danrabbit would be great to get this released by end of this month too :)
> Avoid storing to "Sent" twice for outlook.com

- src/MessageList/MessageListItem.vala
Message header currently shows formatted time in UTC.
This adjusts the time to be local to the OS time zone.
> Use local time in the message header

- src/ConversationList/ConversationListBox.vala
- src/VirtualizingListBox/VirtualizingListBox.vala
Adds a context menu for the single selected conversation.
If we ever support multi-select, this will require some slight refactoring (mainly, to resolve the "state" of the multiple selected items).
> Add conversation list context menu

- data/io.elementary.mail.appdata.xml.in
- src/Composer/ComposerWidget.vala
- src/Composer/ComposerWindow.vala
Closes #745
https://user-images.githubusercontent.com/10796736/147203938-787ef12d-ee9a-45c8-ba8e-c6e793d93481.mp4
> Use subject for window title of new message window

- src/Backend/Session.vala
In the Composer Widget, the `from` dropdown has duplicate entries, these duplicate come from `session.get_own_addresses`.
This solves the symptom by making `get_own_addresses` return a unique list of email addresses.
ref https://github.com/elementary/mail/issues/750
> get_own_addresses return a unique list of email addresses

- data/io.elementary.mail.appdata.xml.in
- src/VirtualizingListBox/VirtualizingListBox.vala
This fixes https://github.com/elementary/mail/issues/734 caused by a regression introduced in https://github.com/elementary/mail/pull/717:
Basically when `model.get_n_items () ` returns `0` and we subtract `1` from it, we end up with an underflow because we are dealing with an `uint` here. So the result of this calculation is `uint.MAX`. The following code then starts to loop from `0` to `uint.MAX` multiple times causing my laptop to fly :smile: 
This PR introduces some changes to avoid this.
> Fix UI freeze because of uint underflow

- data/io.elementary.mail.appdata.xml.in
- src/ConversationList/ConversationItemModel.vala
- src/ConversationList/ConversationListBox.vala
- src/ConversationList/ConversationListItem.vala
- src/FoldersView/FolderSourceItem.vala
- src/Utils.vala
When we are in the Sent folder, we don't want to show the sender's address in the conversation list because this will always be our own address. Instead, we want to display to whom we've sent the mail.
This PR corrects exactly this behavior.
> Show recipient in Sent folder instead of sender

- src/FoldersView/FoldersListView.vala
- src/HeaderBar.vala
- src/MainWindow.vala
- src/MessageList/MessageListBox.vala
- src/WelcomeView.vala
Follow up to #462
Gets rid of some resizing voodoo.
Clean up the welcome screen:
* Layout more similar to Granite 7's Placeholder
* Use Gtk.Show_uri_on_window for better window management stuff
* Easier window moving with window handle
> MainWindow: Use multiple headerbars

- src/MainWindow.vala
Consistent with other strings if it is a concurrent action.
Should be something other than the name if it is just the tooltip.
> MainWindow: Spelling: ellipsis

- docs/meson.build
As mentioned in https://github.com/elementary/mail/pull/794#discussion_r930079796, I guess I will split out the change as a new PR since looks like squash merge is more commonly used here...
Without the change documentation build fails with
```
ComposerWindow.vala:21.36-21.38: error: The symbol `Hdy' could not be found
FoldersListView.vala:26.12-26.14: error: The symbol `Hdy' could not be found
```
```
Application.vala:43.30-43.44: error: The name `GETTEXT_PACKAGE' does not exist in the context of `Mail.Application'
Application.vala:43.47-43.55: error: The name `LOCALEDIR' does not exist in the context of `Mail.Application'
Application.vala:44.39-44.53: error: The name `GETTEXT_PACKAGE' does not exist in the context of `Mail.Application'
Application.vala:45.26-45.40: error: The name …
```
> build: fix documentation build

- README.md
Every other elementary repo correctly lists `meson` as one of the dependencies to build its application. For some reason this is currently missing from the dependency list here.
This PR includes the dependency on meson as done in every other repo.
> Docs: Add curiously omitted dependency on meson to the readme

- src/MessageList/MessageListItem.vala
I have been able to trigger this by changing the selected folder while it is loading.
> MessageListItem: avoid crashing on empty Mime

- src/MessageList/MessageListItem.vala
- Construct with properties
- Update margins etc.
- Use widget specific API (e.g. attach instead add)
> Prep for GTK4 MessageListItem cleanup

- src/MainWindow.vala
Fixes a small issue where you could resize this pane such that controls and contents got cut off
> MainWindow: don't allow pane to shrink past contents

- src/Backend/Session.vala
- src/MainWindow.vala
Now adding an account via settings is reflected by the mail app while running. If no account was previously installed the `WelcomeView` will go away once an account was added. If there were accounts installed previously, the new account will just be added to the sidebar and - in case there was only one account installed - the "All Mailboxes" section will appear.
Also fixes #819
> Handle account adding live

- po/POTFILES
- src/ConversationList/ConversationList.vala
- src/ConversationList/ConversationListBox.vala
- src/MainWindow.vala
- src/MessageList/MessageList.vala
- src/VirtualizingListBox/VirtualizingListBox.vala
- src/meson.build
This is being done in preparation for GTK4
- Derive `MessageListBox` from `Gtk.Box`
- Move corresponding stuff to `MessageListBox` from `MainWindow`
- Cleanup
- Rename to `MessageList`
- Update POTFILES
A few notes:
- The `search_changed` signal of a `Gtk.SearchEntry` has a default delay of 150 ms. I think that's reasonable enough so that we don't have to add another 800 ms of delay. This doesn't really impact performance for small folders, it even makes them seem more reactive and for large folders searching is pretty much broken anyway. Also the delay can be changed in GTK4 if we really would want a longer delay again.
- The `search_entry` and the `filter_button` were set to not be sensitive if no accounts have been added yet. I think this isn't necessary as they can't be focused or …
> Derive MessageListBox from Gtk.Box in preparation for GTK4

- data/application.css
Just a little magic to make it look like headerbars float above scrolled content
> Application.css: add scrolledwindow undershoot

- src/Backend/Account.vala
- src/Backend/Session.vala
- Fix an issue that was introduced with #871 that causes mail to not connect to the network because `NetworkMonitor.network_available` is for some reason `false` in the beginning. To do this we set `Session.online` to true by default (which btw is also the default if it's not set at all but I think it's better to keep explicitly setting it to avoid confusion) 
- Add some debug messages
- Alternatively we could also use GLib.NetworkMonitor which reports a change in the beginning so a connection is established because of the signal connection (might be better but I would leave this to a different PR to get the issue at hand fixed ASAP)
I'm so sorry, I had this commit locally but forgot to push 😬
> Fix an issue that causes mail to never connect to the network

- src/FoldersView/FoldersListView.vala
- src/MessageList/MessageList.vala
* Makes room for the undo toast so it's less likely to cover buttons
* Settings related to the whole app/accounts aren't in the deepest pane, this will probably matter more for responsive/mobile but it makes them less logically connected to the messages list
> Move menu to FoldersListView

- src/MessageList/FolderPopover/FolderPopover.vala
- src/MessageList/FolderPopover/FolderRow.vala
- src/MessageList/MessageList.vala
- src/meson.build
It gets moved into a separate class because it might come in handy later in other places (e.g. moving folders etc.)
Screenshot:
Fixes #904
> Improve move menu and make it searchable

- src/SourceList/CellRendererBadge.vala
I was rebasing a downstream [valadoc patch](https://github.com/NixOS/nixpkgs/pull/241298) and was looking for random projects (which build docs with valadoc) to test my patch and accidently find the `-Ddocumentation=true` build here fails :see_no_evil: 
```
[209/242] Generating docs/full documentation with a custom command
FAILED: docs/full
...
CellRendererBadge.vala: Mail.CellRendererBadge: {{:  error: '../doc/images/cellrendererbadge.png' does not exist
...
Failed: 1 error(s), 4 warning(s)
```
Tested building and browsing the docs:
> CellRendererBadge: Remove reference of non-existent image

- data/mail.metainfo.xml.in
The app name and the mails themselves may be translated to different words in some languages, so I guess we may want to distinguish these two things here
> Metainfo: Distinguish the mails themselves and the app name

- src/Utils.vala
For some mail accounts the grouped archive folder displayed the inbox if no archive was found. That was because calling `get_folder_info` with an empty string returned the Inbox folder for some mail accounts (e.g. `t-online.de` accounts). Now we make sure that we return `null` instead of an empty string in `Utils.strip_folder_full_name` when a given folder uri is empty.
> Fix grouped archive folder

- src/ConversationList/ConversationListItem.vala
Set menu attach widgets so that `action_name` works as expected
while here, use `child` and avoid long lines
> ConversationListItem: set menu attach widget

- src/FoldersView/GroupedFolderSourceItem.vala
Allows to have separate translations ("Archive" the folder is translated differently from "Archive" the verb).
> GroupedFolderSourceItem: Add context to folder names

- src/ConversationList/ConversationList.vala
With undoing working very reliable now, I don't think there is a reason to disable the keyboard accelerators for trashing a message when the ConversationList looses keyboard focus. It only is annoying when clicking once within the message and then being unable to use `Backspace` or `Delete` for trashing it.
Fixes #952
> Don't disable delete accelerators when the ConversationList looses keyboard focus

- src/Composer.vala
- src/MessageList/MessageListItem.vala
Fix some attachments not showing up.
Tries to fix #957  
Only for reference if this doesn't work: the evolution way of getting whether a part is an attachment is (I think) found [here](https://github.com/GNOME/evolution/blob/70d6fcc6c1dcb73a0f8f121df4db9cd782c91a9e/src/em-format/e-mail-part-utils.c#L265)
> Fix some attachments not showing up

- src/Composer.vala
This fixes an issue that occurred when replying to a message received by an alias. Then the pre-selected sender would be the main address.
> Use the actual recipients of a message as sender when replying or forwarding

- src/Dialogs/AliasDialog/Alias.vala
- src/Dialogs/AliasDialog/AliasDialog.vala
- src/FoldersView/AccountSourceItem.vala
Alias:
* Use a vertical form layout with header labels to match the design of other forms
* Make sure the screen reader knows how to describe entries by setting mnemonic_widget
* Placeholder text in forms should contain example content, not explanation text or directions
* Image buttons should have tooltip text (screenreader reads this too)
AliasDialog:
* Subclass Granite.Dialog since we're not doing anything that requires a Hdy.Window
* Dialogs should have a transient parent so they are centered on the parent etc
* Make sure screen reader can read the add button
* Use built-in method for dialog buttons instead of adding window controls manually
> AliasesDialog: screen reader fixes, design tweaks

- src/Application.vala
This fixes #950 which currently renders mail pretty much unusable and is an alternative to #973 that doesn't change the current design. I think it might be worth considering merging and releasing this or at least something similar to #973 since OS8 is still a bit away and in my testing it's not even yet fixed there (neither GTK3 nor GTK4) although some bug reports from webkit suggest it is :shrug: 
As per [webkit documentation](https://trac.webkit.org/wiki/EnvironmentVariables) this
> Force[s] Accelerated Compositing mode to be always off 
While this is of course not an optimal solution I think it should be fine for the mail messages usecase.
> Force disabling webkit compositing mode

- data/io.elementary.mail.apparmor
- data/meson.build
On OS 8 mail crashes by default with these errors when opening an html message:
```
bwrap: Creating new namespace failed: Permission denied
** (io.elementary.mail:8681): ERROR **: 20:09:48.735: Failed to fully launch dbus-proxy: Child process exited with code 1
```
This seems to be caused by changes in how ubuntu configures bubblewrap with apps now requiring apparmor profiles to access it ?
I'm not really sure what's actually going on behind the scenes but as per [this launchpad bug](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844) and my own testing creating an apparmor profile for mail fixes the issue.
> Add apparmor profile

- src/Dialogs/AliasDialog/Alias.vala
I don't think we need to make email addresses translatable. Also use uncapitalized one because it's more common
> Alias: Do not translate placeholder email address

- .github/workflows/ci.yml
stable is now Circe so we can bump webkit vesion
> CI: bump webkit version

- io.elementary.mail.json
libportal is bundled from Platform 8 so we shouldn't need it here anymore
> Flatpak: Use libportal from Platform
