data/org.pantheon.mail.appdata.xml.in

* Change summary to match .desktop
* Update issue tracker URL
* Add Translate URL

Update URLs in appdata

---

data/org.pantheon.mail.gschema.xml

Enable startup notifications in gschema

---

src/ConversationList/ConversationListItem.vala

* Add a bottom box shadow for each item
* whitespace for legibility
* adjust margins
* Use style classes instead of pango
* Set date label and give it a simple format with GLib

Style conversationlistitem

---

src/MainWindow.vala

Add a minimum window size

---

data/io.elementary.mail.gschema.xml
src/MainWindow.vala

* Organize MainWindow.vala
* Create a pane position settings key and bind

Remember position of the folders pane

---

src/meson.build

I'm not quite sure what you guys are up to with this rewrite so I hope that pull requests are welcome 😃

actually install the executable

---

data/io.elementary.mail.appdata.xml.in

Since this is a new codebase, remove all the old Geary stuff and reflect the license of the new codebase

Remove old Geary stuff from appdata

---

src/MessageList/MessageListItem.vala

This works better for me. Emails load much more reliably and aren't as broken.

Use MemoryOutputStream

---

src/WebView.vala
src/WebViewServer.vala
src/meson.build
webkit-extension/Main.vala

Only the DOM knows the requested height of the WebView. Set up some communication between the DOM extension and the UI to set the height of the WebView widget.

Set webview height

---

src/WebView.vala

Also add a `link_activated` signal ready for opening a browser for links that are clicked.

Stop clicked links from trying to load in the email browser

---

src/MessageList/MessageListItem.vala

Probably not the best way to do this, but it does the thing. Maybe @davidmhewitt can make it better since he knows how the web view API works :p

Show images InfoBar

---

data/application.css

Not sure if this should be merged, but putting this here for visibility. Probably needs to be played with for a while to see how it feels in practice. Looks like:

Make collapsed cards more compact

---

src/Composer/ComposerWindow.vala

A thing we can type in! :tada:

Add WebView to composer

---

src/Composer/ComposerWindow.vala

Probably we want some more complicated regex or something at some point to verify that there's a valid email address, but this is a start :)

ComposerWindow: set send button insensitive while to entry is empty

---

data/application.css
src/Composer/ComposerWindow.vala

ComposerWindow: Add a mechanism to reveal extra fields

---

data/io.elementary.mail.gschema.xml
src/Application.vala

Reads and sets the window size and position even when maximized so that when unmaximizing we try to restore back to the last known unmaximized size and position.
Doesn't write settings for window position or size when maximized for the same reason.

Save maximized state

---

src/Composer/ComposerWidget.vala
src/Composer/ComposerWindow.vala
src/Composer/InlineComposer.vala

Fields don''t get auto populated in the inline composer yet. Just moving the fields into the parent class and hiding the subject box in the inline composer.

Add the To and CC fields to the inline composer

---

src/client/accounts/AccountDialogRemoveConfirmPane.vala
src/client/dialogs/OpenAttachmentDialog.vala
src/client/dialogs/PasswordDialog.vala

Updates the Free Software Foundation's address in license headers

Update FSF address

---

src/ConversationList/ConversationListItem.vala

Remove date time method here since it's in the library now

Use Granite.DateTime.get_relative_datetime

---

src/Backend/Session.vala

Makes my 2FA google account work in the re-written mail client, where it didn't previously.

Rewrite: Implement get_oauth2_access_token_sync

---

src/MessageList/MessageListBox.vala

MessageListBox: Add a placeholder when empty

---

data/io.elementary.mail.gschema.xml
src/Application.vala

Switch window state to tuples to appease Corentin

---

data/io.elementary.mail.gschema.xml
src/Application.vala

Since we always change these together

Settings: Use an array for window size

---

src/Backend/TrashHandler.vala
src/ConversationList/ConversationItemModel.vala
src/ConversationList/ConversationListBox.vala
src/ConversationList/ConversationListStore.vala
src/MainWindow.vala
src/VirtualizingListBox/VirtualizingListBox.vala
src/VirtualizingListBox/VirtualizingListBoxModel.vala
src/meson.build

Fixes #276 
This is ready for review. There seems to be an issue with which item is selected in the listbox after an item is deleted, but this appears to be an issue with the new listbox implementation (that I'll look at fixing separately) rather than this branch.

Undo toast for deleted messages

---

data/io.elementary.mail.gschema.xml
src/FoldersView/FoldersListView.vala

FolderListView: Restore previously selected folder

---

src/ConversationList/ConversationItemModel.vala
src/ConversationList/ConversationListItem.vala

ConversationList: Show replied status

---

src/MessageList/MessageListItem.vala

MessageListItem: Star a message by clicking the star icon

---

src/ConversationList/ConversationListItem.vala

https://github.com/elementary/icons/commit/2fbb88e1e63dceb6b7b706daeb9866785f11ddb0

ConversationListItem: use mail-forwarded-symbolic

---

src/Composer/ComposerWidget.vala

Just kind of bullshitting the secondary text. Could use some help there

ComposerWidget: Show a warning when there is no subject

---

src/HeaderBar.vala

Headerbar: Add accelerators to Mark menu items

---

src/Composer/ComposerWidget.vala

Yes, the branch name should describe the fix, not the problem. I was in a hurry :man_shrugging:

Fix new message functionality (#402)

---

webkit-extension/MailPage.vala
webkit-extension/meson.build

Remove the use of deprecated API and use Javascriptcore instead API instead

webkit-extension: Do not use the deprecated DOM API

---

src/FoldersView/AccountSourceItem.vala
src/FoldersView/FoldersListView.vala

Actually set the SourceItem as selected

FoldersListView: Restore selection of the previous folder

---

src/Backend/Session.vala
src/HeaderBar.vala
src/MainWindow.vala

Set search sensitivity when accounts are added/removed

---

src/MessageList/MessageListItem.vala
src/Utils.vala
vapi/camel-1.2.vapi

MessageListItem: use Hdy.Avatar

---

src/ConversationList/ConversationListItem.vala

Does this need to be blue or do we actually want it to be accent color?

ConversationListItem: Use accent color for unread badge

---

src/ConversationList/ConversationListItem.vala

Take the opportunity to use the new code style when possible.

ConversationListItem: Align the date label to the right

---

data/icons/128.svg
data/icons/16.svg
data/icons/24.svg
data/icons/32.svg
data/icons/48.svg
data/icons/64.svg
data/io.elementary.mail.desktop.in
data/meson.build

Install icons

---

.github/workflows/main.yml
io.elementary.mail.yml

Add flatpak

---

src/ConversationList/ConversationListBox.vala

Fixes #278 
Does 5 seconds seem like a reasonable value?

Automatically mark messages as read

---

src/MessageList/MessageListItem.vala

Don't load images by default in junk folder

---

src/ConversationList/ConversationListBox.vala
src/MainWindow.vala

Fixes #256 
We'll probably need to build a class that builds more clever search query strings in the future, as this currently just checks whether the sender, subject or message body contains the search query, but it's a reasonable start to get the search feature off the ground.

Initial rudimentary search ability

---

src/ConversationList/ConversationListItem.vala

ConversationListItem: Avoid recomputing the number of messages

---

src/ConversationList/ConversationListStore.vala

Vala sugar syntax is better than unsigned overflow.

ConversationListStore: Use uint.MAX instead of -1u

---

.github/workflows/gettext.yml

The translation files seem to remain old for 2 years :sweat_smile:

Add Gettext Upgates

---

src/MainWindow.vala

Fix "Message Deleted" not shown as translated

---

src/ConversationList/ConversationListItem.vala

As per https://github.com/elementary/stylesheet/issues/876

ConversationListItem: Add flat class to badge label

---

meson.build
src/Dialogs/InsertLinkDialog.vala

InsertLinkDialog: Gtk.Dialog → Granite.Dialog

---

src/FoldersView/GroupedFolderSourceItem.vala

This PR adds the unread badge to the grouped inbox.

Show unread count of grouped Inbox

---

.github/workflows/ci.yml
io.elementary.mail.yml

* Only run CI on PRs
* Update flatpak action
* Make lint use checkout v2

CI: update flatpak-action

---

po/es.po
src/FoldersView/GroupedFolderSourceItem.vala
src/FoldersView/SessionSourceItem.vala

This PR builds upon the previous Grouped Folder PR's and adds support for the well known folders Archive, Draft and Sent:

Grouped Folders Added: Archive

---

src/ConversationList/ConversationListBox.vala

During app startup `folder_selected` is fired multiple times. This causes the folders to be re-loaded and therefore the conversations and threads to be cleared.
All of this happens asynchronously, therefore we need to lock access to the thread instance variable to avoid accidental race conditions which lead to an application crash.

Lock access to threads to avoid race conditions

---

io.elementary.mail.yml

Fixes build issues with latest runtime

flatpak: Bump EDS to 3.40.2

---

src/ConversationList/ConversationItemModel.vala
src/ConversationList/ConversationListItem.vala

This allows to easily see the summary of a message

ConversationListBox: Add a tooltip when hovering a message

---

src/Composer/ComposerWidget.vala
src/Composer/InlineComposer.vala

This PR makes sure the subject is set and shown when replying to an email. Fixes #601.

Set and show subject on Reply

---

README.md

README: Bump granite version

---

src/Composer/ComposerWidget.vala

Fixes https://github.com/elementary/mail/issues/613

Make composer insensitive during send

---

data/io.elementary.mail.appdata.xml.in
src/Backend/Session.vala
src/Composer/ComposerWidget.vala
src/MainWindow.vala
src/WebView.vala

Fixes https://github.com/elementary/mail/issues/610

Edit draft

---

data/io.elementary.mail.appdata.xml.in
src/MainWindow.vala

This PR is a proposal to fix https://github.com/elementary/mail/issues/547
**Before**
**After**

Moved undo toast to message view

---

data/io.elementary.mail.appdata.xml.in

Plus black foreground text. I experimented with a really dark "yellow" for the foreground but it looked like an ugly brown to me. Not totally opposed to the idea if we can get something nice.

AppData: Use Banana 300 for brand banner

---

data/io.elementary.mail.appdata.xml.in
meson.build

Fixes an issue with closing empty drafts, a startup crash, a rendering issue, and some other neat stuff

Release 6.1.1

---

src/Backend/Session.vala

Use the right one already provided by Camel

Session: do not use our own Camel.Sasl subclass

---

data/icons/mail-filter-active.svg
data/icons/mail-filter.svg
data/io.elementary.mail.gresource.xml
src/HeaderBar.vala

Not the best icons ever in the world, but it's something :sweat_smile: 
Includes other comments from review

Add icons, style adjustments

---

data/io.elementary.mail.appdata.xml.in

Office 365 -> Microsoft 365

---

data/io.elementary.mail.appdata.xml.in
src/Application.vala

This fixes #721 
Once this is merged, we should check (and fix) if we do have the same issue in Tasks as well as Calendar.

Fix crash of background process

---

src/Composer/ComposerWidget.vala

Fixes compilation with latest valac.
Closes #762

ComposerWidget: Make ACTION_ENTRIES private

---

data/icons/128.svg
data/icons/16.svg
data/icons/24.svg
data/icons/32.svg
data/icons/48.svg
data/icons/64.svg

- Match roundness with new mail
- Make sure we're using latest color palette
- clean up while we're here
Todo:

Round app icon

---

src/Dialogs/InsertLinkDialog.vala

Fixes #810 
My first contribution to a community project, so if i did something wrong or disregarded any best practices please let me know. Also any feedback is welcome and appreciated :)

Make a link containing '%' valid (Fix for #810)

---

data/mail.metainfo.xml.in
meson.build

Contains an important crash fix

Release 7.0.1

---

po/POTFILES
src/FoldersView/AccountSavedState.vala
src/FoldersView/AccountSourceItem.vala
src/FoldersView/FolderSourceItem.vala
src/FoldersView/FoldersListView.vala
src/FoldersView/GroupedFolderSourceItem.vala
src/FoldersView/SessionSourceItem.vala
src/SourceList/CellRendererBadge.vala
src/SourceList/CellRendererExpander.vala
src/SourceList/SourceList.vala
src/meson.build

Since SourceList isn't in Granite 7, we need to make it internal to port to Gtk 4

Make SourceList internal

---

.github/workflows/ci.yml
.github/workflows/merge.yml

No functional change here, just reflects the repository redirect.

Update flatpak actions to new namespace

---

src/Composer/ComposerWidget.vala

Gtk 4 prep
* Replace grids with boxes where appropriate
* construct with properties
* Set all margins explicitly

ComposerWidget: replace grid/box, code style

---

src/ConversationList/ConversationListItem.vala

- Update margins
- Construct with properties

ConversationListItem: Small updates for gtk4

---

src/MessageList/AttachmentButton.vala

- Update margins etc.
- Construct with properties
- Replace individual Gtk.MenuItems with GLib.Menu

AttachmentButton: Updates for gtk4

---

data/icons/mail-filter-symbolic.svg
src/ConversationList/ConversationList.vala

This seems more obvious now that the these are in the same class. Update this icon while we're here

ConversationList: put the filter menu next to the searchbar

---

src/Composer.vala

Composer: add keyboard shortcuts

---

src/Application.vala
src/Composer.vala
src/MainWindow.vala
src/MessageList/MessageList.vala

Also fix some places where we assume that `active_window` is a `MainWindow` and not a `Composer`

Composer: set parent internally, use present

---

src/Dialogs/InsertLinkDialog.vala

- Construct with properties
- Handle  nullable variable

InsertLinkDialog: Update for GTK4

---

src/Composer.vala

Composer: Remove Ctrl + Backspace/Delete shortcuts

---

src/FoldersView/AccountSourceItem.vala
src/FoldersView/FolderSourceItem.vala
src/SourceList/SourceList.vala

- Sorts special folder to the top of the accounts folder tree
- There they currently are sorted in this order:
- INBOX
- DRAFTS
- OUTBOX
- SENT
- ARCHIVE
- TRASH
- JUNK
Fixes #903

Sort special folders to top

---

debian/control

Depend on new enough portals for creating autostart using the background portal

Control add portals to depends

---

data/ConversationListItem.css
data/io.elementary.mail.gresource.xml
src/ConversationList/ConversationListItem.vala

For #930
Some copy+paste from notifications indicator.
I decided to use symbolic icons and AFAIK there's no mail-archive-symbolic icon, so it looks weird for now :(

Improve style of swipe buttons

---

data/icons/mail-archive/16.svg
data/icons/mail-archive/24.svg
data/icons/mail-archive/48.svg
data/icons/mail-archive/symbolic.svg
data/io.elementary.mail.gresource.xml

Add these non-fdo icons to Mail

Gresource: add mail-archive

---

data/ConversationListItem.css
src/ConversationList/ConversationListItem.vala

Also support RTL and make sure values scale with text size

ConversationListItem: DRY swipe affordances

---

src/Dialogs/AliasDialog/Alias.vala
src/Dialogs/AliasDialog/AliasDialog.vala

My attempt to improve the design.

Improve aliases design

---

debian/control

Pushed a separate deb-packaging-jammy branch

Update for Noble

---

data/io.elementary.mail.gschema.xml
src/Application.vala
src/MainWindow.vala

GTK 4/Wayland prep. Can't set window position in Wayland

gschema: remove window position

---

README.md

In order to get this building on Debian/bookworm, I had to install these.

update list of dependencies in README

---

.github/workflows/ci.yml

Since we're not shipping the flatpak, make sure we build against the OS

CI: build against OS

---

src/MessageList/MessageListItem.vala

* explicit h/v properties
* Use infobar.revealed instead of no_show_all
* child property
* Click gesture for header click event. Doesn't absorb events from child widgets, so remove those workarounds

MessageListItem: GTK4 prep

---

data/io.elementary.mail.desktop.in

This is a [fd.o icon](https://specifications.freedesktop.org/icon-naming-spec/latest/) so no need to ship it ourselves

Launcher: add icon for compose action
